name: Publish new Docker image

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout pushed ref and fetch all tags
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Configure git user identity
        run: |
          git config user.name "GitHub Actions on behalf of $(jq -r '.pusher.name' "$GITHUB_EVENT_PATH")"
          git config user.email "$GITHUB_ACTION@actions.noreply.github.com"

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u "$DOCKER_USERNAME" --password-stdin <<<"$DOCKER_PASSWORD"

      - run: make publish
